# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/home/guansj/GeneAIG/GeneMltiAIG

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/home/guansj/GeneAIG/GeneMltiAIG

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/home/guansj/GeneAIG/GeneMltiAIG/CMakeFiles /mnt/home/guansj/GeneAIG/GeneMltiAIG//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/home/guansj/GeneAIG/GeneMltiAIG/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ec_expand

# Build rule for target.
ec_expand: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ec_expand
.PHONY : ec_expand

# fast build rule for target.
ec_expand/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ec_expand.dir/build.make CMakeFiles/ec_expand.dir/build
.PHONY : ec_expand/fast

src/aag.o: src/aag.cpp.o

.PHONY : src/aag.o

# target to build an object file
src/aag.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ec_expand.dir/build.make CMakeFiles/ec_expand.dir/src/aag.cpp.o
.PHONY : src/aag.cpp.o

src/aag.i: src/aag.cpp.i

.PHONY : src/aag.i

# target to preprocess a source file
src/aag.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ec_expand.dir/build.make CMakeFiles/ec_expand.dir/src/aag.cpp.i
.PHONY : src/aag.cpp.i

src/aag.s: src/aag.cpp.s

.PHONY : src/aag.s

# target to generate assembly for a file
src/aag.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ec_expand.dir/build.make CMakeFiles/ec_expand.dir/src/aag.cpp.s
.PHONY : src/aag.cpp.s

src/filters.o: src/filters.cpp.o

.PHONY : src/filters.o

# target to build an object file
src/filters.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ec_expand.dir/build.make CMakeFiles/ec_expand.dir/src/filters.cpp.o
.PHONY : src/filters.cpp.o

src/filters.i: src/filters.cpp.i

.PHONY : src/filters.i

# target to preprocess a source file
src/filters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ec_expand.dir/build.make CMakeFiles/ec_expand.dir/src/filters.cpp.i
.PHONY : src/filters.cpp.i

src/filters.s: src/filters.cpp.s

.PHONY : src/filters.s

# target to generate assembly for a file
src/filters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ec_expand.dir/build.make CMakeFiles/ec_expand.dir/src/filters.cpp.s
.PHONY : src/filters.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ec_expand.dir/build.make CMakeFiles/ec_expand.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ec_expand.dir/build.make CMakeFiles/ec_expand.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ec_expand.dir/build.make CMakeFiles/ec_expand.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/validation.o: src/validation.cpp.o

.PHONY : src/validation.o

# target to build an object file
src/validation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ec_expand.dir/build.make CMakeFiles/ec_expand.dir/src/validation.cpp.o
.PHONY : src/validation.cpp.o

src/validation.i: src/validation.cpp.i

.PHONY : src/validation.i

# target to preprocess a source file
src/validation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ec_expand.dir/build.make CMakeFiles/ec_expand.dir/src/validation.cpp.i
.PHONY : src/validation.cpp.i

src/validation.s: src/validation.cpp.s

.PHONY : src/validation.s

# target to generate assembly for a file
src/validation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ec_expand.dir/build.make CMakeFiles/ec_expand.dir/src/validation.cpp.s
.PHONY : src/validation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ec_expand"
	@echo "... src/aag.o"
	@echo "... src/aag.i"
	@echo "... src/aag.s"
	@echo "... src/filters.o"
	@echo "... src/filters.i"
	@echo "... src/filters.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/validation.o"
	@echo "... src/validation.i"
	@echo "... src/validation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

